name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build --prod

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Docker credentials
        run: gcloud auth configure-docker

      - name: Build Docker image
        run: |
          echo "Building the Docker image..."
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/angular-repo/angular-image:${{ github.sha }} .
          docker images

      - name: Push Docker image
        run: |
          echo "Pushing the Docker image..."
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/angular-repo/angular-image:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          echo "Deploying to Cloud Run.."
          gcloud run deploy angular-service\
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/angular-repo/angular-image:${{ github.sha }} \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
