name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build --prod

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          log_http: true

      - name: Set up Docker credentials
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build Docker image
        run: |
          echo "GCP Project ID: steel-magpie-426708-v2"
          docker build -t us-central1-docker.pkg.dev/steel-magpie-426708-v2/angular-repo/angular-image:${{ github.sha }} .

      - name: Push Docker image
        run: docker push us-central1-docker.pkg.dev/steel-magpie-426708-v2/angular-repo/angular-image:${{ github.sha }}

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v3
        with:
          service: angular-cloudrun
          region: us-central1
          # NOTE: If using a pre-built image, update the image name here
          image: us-central1-docker.pkg.dev/steel-magpie-426708-v2/angular-repo/angular-image:${{ github.sha }} \
